project_name: snyk-iac-rules

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    env:
    - CGO_ENABLED=0
    goos:
    - windows
    - linux
    - darwin
    goarch:
    - amd64
    - arm64

archives:
  - id: default
    files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^refactor:'
    - '^Merge pull request'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  # If set to true, will not auto-publish the release.
  draft: false

  # Header template for the release body.
  # Defaults to empty.
  header: |
    ## snyk-iac-rules ({{ .Date }})

    Welcome to this new release!

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

brews:
  -
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: false
    # GitHub repository to push the formula to
    tap:
      owner: snyk
      name: homebrew-tap

    homepage: "https://snyk.io/"
    license: Apache-2.0
    description: "Write, debug, test, and bundle custom rules for Snyk IaC."

scoop:
  # If set to auto, the release will not be uploaded to the scoop bucket
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Default is false.
  skip_upload: false

  # Repository to push the app manifest to.
  bucket:
    owner: snyk
    name: scoop-snyk

  homepage: "https://snyk.io/"
  license: Apache-2.0
  description: "Write, debug, test, and bundle custom rules for Snyk IaC."

# Publishes the deb and rpm files to the GitHub releases page.
nfpms:
  - bindir: /usr/bin
    description: "Write, debug, test, and bundle custom rules for Snyk IaC."
    formats:
      - deb
      - rpm
    homepage: https://github.com/snyk/snyk-iac-custom-rules
    license: Apache-2.0

announce:
  twitter:
    enabled: false
  slack:
    enabled: false
  reddit:
    enabled: false
