@startuml
skinparam activity {
    FontColor          white
    AttributeFontColor white
    FontSize           15
    AttributeFontSize  15
    AttributeFontname  Corbel
    BackgroundColor    #527BC6
    BorderColor        black
    ArrowColor         #222266
}
title Build and use your own custom rules

partition snyk/iac-rules {
    partition development {
        (*) -r> "generate templates"
        -r>"write a rule in Rego"
        partition unit-testing {
              -r> "prepare a fixture file"
              -r> "write unit tests for the rule"
              -r> "run the tests against a fixture file"
        }
    }
    ---> if "        do the tests pass?" then
     partition build {
        -->[ yes] "build the bundle"
     }
    partition configuration {
        ---> set the container registry URL
        note right
            You can configure this via:
            1. the UI
            2. the API
            3. the CLI
        end note
    }
    partition distribution {
        -d> "push the bundle to a container registry"
        note right
            The Container Registry
            must support OCI Artifacts
        end note
    }
}
partition scanning {
    --> run 'snyk iac test' with Snyk CLI
}
    -r> (*)
    else
        endif
    --> [ no] "write unit tests for the rule"
@enduml