name: 'Setup Shellspec testing'
description: 'Sets up Shellspec testing by installing the Snyk CLI, Shellspec, and building the SDK.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install Snyk with npm
      shell: bash
      run: |
        echo "node_version: ${{ matrix.node_version }}"
        node -v
        echo "install snyk with npm"
        npm install -g snyk

    - uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build custom rules SDK
      shell: bash
      run: go build -o snyk-iac-rules .

    - name: Install shellspec
      shell: bash
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- -y
        sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
        ls -la ${HOME}/.local/lib/shellspec
        echo "shellspec symlink:"
        ls -la /usr/local/bin/shellspec
        /usr/local/bin/shellspec --version
        which shellspec
        shellspec --version
